### ISSUE TITLE
Add image examples of bot

### ISSUE THREAD

**Issue by david-shiko** [Mortafix/AutoConv-Telegram-Python#4]
Please add some images/screenshots of how it's look after an installing.

**Comment by Mortafix** [comment]
You can find two different working example on Telegram, specified on the README.
This is a showcase bot, [@autobot](https://t.me/autoconv_bot).
This is a personal bot, [@popcorn](https://t.me/poppycorn_bot).

If you have any other requests of images/screenshot, reopen this thread
